name:                social-network-simulation
version:             0.1.0.0
github:              "As4d/haskell-social-network-simulation"
license:             BSD-3-Clause
author:              "Asad Ali Khan"
maintainer:          "asadkhan91003@gmail.com"
copyright:           "2025 Asad Ali Khan"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/As4d/haskell-social-network-simulation#readme>

dependencies:
- base >= 4.7 && < 5
- time

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  social-network-simulation-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - social-network-simulation

tests:
  social-network-simulation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - social-network-simulation
